---
# Project Information
site_name: DeepSetStats
site_author: David Amat
site_description: Deep Learning for Tennis Statistical Retrieval

# Repository information
repo_name: DavidAmat/deepsetstats
repo_url: https://github.com/DavidAmat/deepsetstats
edit_uri: ""

# Copyright
copyright: Copyright &copy; 2020 David Amat

# Configuration
theme:
  name: material
  icon:
    repo: fontawesome/brands/github
  features:
    - navigation.instant
    - navigation.tabs
  language: en

# Footer
extra:
  social:
    - icon: fontawesome/brands/github
      link: https://github.com/DavidAmat
      name: DavidAmat on GitHub

# Page tree
nav:
  - Home: index.md
